name = "hilu-website"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
TURNSTILE_SECRET_KEY = "0x4AAAAAAB2-jIIkTD7xWkHe3Hb3Cf4CQqE"

[[d1_databases]]
binding = "hilu_db"
database_name = "hilu-db"
database_id = "8a24b4a3-a703-43ef-a378-993019cfb93f"