name = "hilu-website"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
TURNSTILE_SECRET_KEY = "0x4AAAAAAB2-jIIkTD7xWkHe3Hb3Cf4CQqE"

[[d1_databases]]
binding = "hilu_db"
database_name = "hilu-db"
database_id = "8a24b4a3-a703-43ef-a378-993019cfb93f"

# Cron Triggers - Tự động chạy theo lịch
[triggers]
# Production: Chạy mỗi ngày lúc 7h sáng (giờ Việt Nam)
# 7h sáng VN (UTC+7) = 0h UTC
crons = ["0 0 * * *"]

# Các tùy chọn khác (uncomment để dùng):
# Test mỗi 2 phút:
# crons = ["*/2 * * * *"]

# Chạy mỗi giờ:
# crons = ["0 * * * *"]

# Chạy mỗi tuần vào thứ 2, 7h sáng VN:
# crons = ["0 0 * * MON"]

# Chạy 2 lần/ngày (7h sáng và 7h tối VN):
# crons = ["0 0 * * *", "0 12 * * *"]